// Static gallery data — photos served from /public/images/gallery/{slug}/
// Add more categories as photos are provided

export interface GalleryPhoto {
  file: string
  title: string
}

const BASE = '/images/gallery'

export const GALLERY: Record<string, GalleryPhoto[]> = {
  tapiceria: [
    { file: 'banqueta-en-x-capitoneada.jpg', title: 'Banqueta en X capitoneada' },
    { file: 'butaca-chester.jpg', title: 'Butaca Chester' },
    { file: 'butaca-francesa-capitoneada.jpg', title: 'Butaca Francesa capitoneada' },
    { file: 'butaca-paulina-tapizada-con-tela-easy-clean.jpg', title: 'Butaca Paulina tapizada con tela easy clean' },
    { file: 'butaca-princesita.jpg', title: 'Butaca Princesita' },
    { file: 'colchonetas-tela-impermeable.jpg', title: 'Colchonetas tela impermeable' },
    { file: 'juego-de-exterior-con-tela-anti-manchas-en-madera-lapacho.jpg', title: 'Juego de exterior con tela anti manchas en madera lapacho' },
    { file: 'juego-de-exterior-de-mesa-y-bancos-en-eucaliptus.jpg', title: 'Juego de exterior de mesa y bancos en eucaliptus' },
    { file: 'juego-de-exterior-en-lapacho-con-pergola.jpg', title: 'Juego de exterior en lapacho con pérgola' },
    { file: 'juego-de-exterior-en-lapacho-lustrado-oscuro.jpg', title: 'Juego de exterior en lapacho lustrado oscuro' },
    { file: 'juego-de-exterior-en-lapacho.jpg', title: 'Juego de exterior en lapacho' },
    { file: 'juego-de-exterior-tela-impermeable.jpg', title: 'Juego de exterior, tela impermeable' },
    { file: 'juego-de-sillones-con-posabrazos-en-lapacho-con-almohadones.jpg', title: 'Juego de sillones con posabrazos en lapacho con almohadones' },
    { file: 'juego-de-sillones-sin-posabrazos-en-madera-eucaliptus.jpg', title: 'Juego de sillones sin posabrazos en madera eucaliptus' },
    { file: 'living-exterior-en-lapacho-con-pergola-.jpg', title: 'Living exterior en lapacho con pérgola' },
    { file: 'mecedora-nordica.jpg', title: 'Mecedora Nórdica' },
    { file: 'reposeras-con-colchoneta.jpg', title: 'Reposeras con colchoneta' },
    { file: 'reposeras-para-piscinas-con-colchoneta.jpg', title: 'Reposeras para piscinas con colchoneta' },
    { file: 'respaldo-de-cama-italia-tapizado-terciopelo.jpg', title: 'Respaldo de cama Italia tapizado terciopelo' },
    { file: 'respaldo-de-cama-torneado.jpg', title: 'Respaldo de cama torneado' },
    { file: 'silla-tapizada-total-capitoneada.jpg', title: 'Silla tapizada total capitoneada' },
    { file: 'silla-tapizada-total-con-funda.jpg', title: 'Silla tapizada total con funda' },
    { file: 'silla-tapizada-total-con-tachas-en-respaldo.jpg', title: 'Silla tapizada total con tachas en respaldo' },
    { file: 'silla-tapizado-total-y-banco-modelo-mane.jpg', title: 'Silla tapizado total y banco modelo Mane' },
    { file: 'sillas-inglesas.jpg', title: 'Sillas Inglesas' },
    { file: 'sillas-tapizado-total-con-fundas-con-pestana.jpg', title: 'Sillas tapizado total con fundas, con pestaña' },
    { file: 'sillones-clasicos-con-funda.jpg', title: 'Sillones clásicos con funda' },
    { file: 'sillones-con-posabrazos-a-pedido-del-cliente.jpg', title: 'Sillones con posabrazos a pedido del cliente' },
    { file: 'sillones-con-posabrazos-mas-bajo.jpg', title: 'Sillones con posabrazos más bajo' },
    { file: 'sillones-con-tablitas-a-pedido-del-cliente-en-madera-eucaliptus.jpg', title: 'Sillones con tablitas a pedido del cliente en madera eucaliptus' },
    { file: 'sillones-de-tres-cuerpos-con-varillas-verticales-en-lapacho.jpg', title: 'Sillones de tres cuerpos con varillas verticales en lapacho' },
    { file: 'sillones-modelo-fio-con-funda.jpg', title: 'Sillones modelo Fio con funda' },
    { file: 'sillones-sin-posabrazos-con-almohadones.jpg', title: 'Sillones sin posabrazos con almohadones' },
    { file: 'sillon-2-cuerpos-nordico.jpg', title: 'Sillón 2 cuerpos Nórdico' },
    { file: 'sillon-chester-co-madera-a-la-vista.jpg', title: 'Sillón Chester con madera a la vista' },
    { file: 'sillon-chester-de-cuero.jpg', title: 'Sillón Chester de cuero' },
    { file: 'sillon-guillermina.jpg', title: 'Sillón Guillermina' },
    { file: 'sillon-lucia-tapizado-en-terciopelo.jpg', title: 'Sillón Lucia, tapizado en terciopelo' },
    { file: 'sillon-con-asiento-doble.jpg', title: 'Sillón con asiento doble' },
    { file: 'sillon-con-funda-lucia.jpg', title: 'Sillón con funda Lucia' },
    { file: 'sillon-con-funda-de-lino.jpg', title: 'Sillón con funda de lino' },
    { file: 'sillon-con-funda-con-pestana-chica.jpg', title: 'Sillón con funda, con pestaña chica' },
    { file: 'sillon-con-funda-tela-anti-manchas.jpg', title: 'Sillón con funda, tela anti manchas' },
    { file: 'sillon-con-pestana-ancha.jpg', title: 'Sillón con pestaña ancha' },
    { file: 'sillon-con-posabrazos-en-madera-eucaliptus.jpg', title: 'Sillón con posabrazos en madera eucaliptus' },
    { file: 'sillon-cubo-con-almohadones.jpg', title: 'Sillón cubo con almohadones' },
    { file: 'sillon-curvo-en-alamo.jpg', title: 'Sillón curvo en álamo' },
    { file: 'sillon-de-cuero-y-tachas.jpg', title: 'Sillón de cuero y tachas' },
    { file: 'sillon-en-l-con-botones.jpg', title: 'Sillón en L con botones' },
    { file: 'sillon-en-l-con-funda-y-pestana.jpg', title: 'Sillón en L con funda y pestaña' },
    { file: 'sillon-recto-y-puf-italia.jpg', title: 'Sillón recto y puf Italia' },
    { file: 'sillon-semi-circulo-en-lapacho.jpg', title: 'Sillón semi círculo en lapacho' },
    { file: 'sillon-semicirculo-frente-2.10-con-almohadones.jpg', title: 'Sillón semicírculo frente 2.10 con almohadones' },
    { file: 'sillon-sin-posabrazos-de-frente-en-eucaliptus.jpg', title: 'Sillón sin posabrazos de frente en eucaliptus' },
  ],
  'pergolas-y-decks': [
    { file: 'deck-con-esquinero-en-madera-lapacho.jpg', title: 'Deck con esquinero en madera lapacho' },
    { file: 'deck-en-lapacho-lustrado.jpg', title: 'Deck en lapacho lustrado' },
    { file: 'deck-en-madera-lapacho.jpg', title: 'Deck en madera lapacho' },
    { file: 'deck-en-madera-lapacho-2.jpg', title: 'Deck en madera lapacho con living' },
    { file: 'pergola-con-sombra-y-policarbonato.jpg', title: 'Pérgola con sombra y policarbonato' },
    { file: 'pergola-con-sombra-y-policarbonato-2.jpg', title: 'Pérgola con sombra y policarbonato 2' },
    { file: 'pergola-con-sombra.jpg', title: 'Pérgola con sombra' },
    { file: 'pergola-con-sombra1.jpg', title: 'Pérgola con sombra (jardín)' },
    { file: 'pergola-con-sombra2.jpg', title: 'Pérgola con sombra (efecto luces)' },
    { file: 'pergola-de-troncos-con-sombra.jpg', title: 'Pérgola de troncos con sombra' },
    { file: 'pergola-exterior-en-madera-eucaliptus.jpg', title: 'Pérgola exterior en madera eucaliptus' },
    { file: 'pergola-sin-sombra-en-pino-con-tratamiento-cca-1.jpg', title: 'Pérgola sin sombra en pino con tratamiento CCA' },
    { file: 'pergola-y-deck-en-madera-lapacho.jpg', title: 'Pérgola y deck en madera lapacho' },
  ],
  decoracion: [
    { file: 'aparadores.jpg', title: 'Aparadores' },
    { file: 'arcones.jpg', title: 'Arcones' },
    { file: 'atril-para-lcd.jpg', title: 'Atril para LCD' },
    { file: 'atril-para-pintor.jpg', title: 'Atril para pintor' },
    { file: 'bancos.jpg', title: 'Bancos' },
    { file: 'banquetas.jpg', title: 'Banquetas' },
    { file: 'banos.jpg', title: 'Baños' },
    { file: 'bares.jpeg', title: 'Bares' },
    { file: 'barras.jpg', title: 'Barras' },
    { file: 'bibliotecas.jpg', title: 'Bibliotecas' },
    { file: 'bodegueros.jpg', title: 'Bodegueros' },
    { file: 'butacas.jpg', title: 'Butacas' },
    { file: 'camas.jpg', title: 'Camas' },
    { file: 'cocinas.jpg', title: 'Cocinas' },
    { file: 'comodas.jpg', title: 'Cómodas' },
    { file: 'escritorios.jpg', title: 'Escritorios' },
    { file: 'espejos.jpg', title: 'Espejos' },
    { file: 'mesas-auxiliares.jpg', title: 'Mesas Auxiliares' },
    { file: 'mesas-de-arrimo.jpg', title: 'Mesas de Arrimo' },
    { file: 'mesas-de-comedor.jpg', title: 'Mesas de Comedor' },
    { file: 'mesas-de-living.jpg', title: 'Mesas de Living' },
    { file: 'mesas-de-luz.jpeg', title: 'Mesas de luz' },
    { file: 'racks.jpg', title: 'Racks' },
    { file: 'respaldos.jpg', title: 'Respaldos' },
    { file: 'roperos.jpg', title: 'Roperos' },
    { file: 'sillas.jpg', title: 'Sillas' },
    { file: 'sillones-tapizados.jpg', title: 'Sillones Tapizados' },
    { file: 'sillones-de-exterior.jpg', title: 'Sillones de Exterior' },
    { file: 'taburetes.jpg', title: 'Taburetes' },
    { file: 'trinchantes.jpg', title: 'Trinchantes' },
  ],
  escritorios: [
    { file: 'amoblamiento-para-playroom.jpg', title: 'Amoblamiento para playroom' },
    { file: 'cama-y-escritorio-personalizado.jpg', title: 'Cama y escritorio personalizado' },
    { file: 'dressoire-con-cajoneras-en-alamo-con-diseno-del-cliente.jpg', title: 'Dressoire con cajoneras en álamo con diseño del cliente' },
    { file: 'escritorio-delfi-con-moldura.jpg', title: 'Escritorio Delfi con moldura' },
    { file: 'escritorio-delfi-con-repisa-blanco-1.jpg', title: 'Escritorio Delfi con repisa blanco' },
    { file: 'escritorio-a-pedido-del-cliente-con-moldura-en-alamo1.jpg', title: 'Escritorio a pedido del cliente con moldura en álamo' },
    { file: 'escritorio-arco-de-futbol.jpg', title: 'Escritorio arco de fútbol' },
    { file: 'escritorio-combinando-tonos.jpg', title: 'Escritorio combinando tonos' },
    { file: 'escritorio-con-alzada-con-cajonera-central-con-pizarras-de-corcho.jpg', title: 'Escritorio con alzada con cajonera central con pizarras de corcho' },
    { file: 'escritorio-de-ninos-en-alamo.jpg', title: 'Escritorio de niños en álamo' },
    { file: 'escritorio-en-u-con-estante.jpg', title: 'Escritorio en U con estante' },
    { file: 'escritorio-en-cedro-con-cajon.jpg', title: 'Escritorio en cedro con cajón' },
    { file: 'escritorio-frances-con-banqueta-tapizada.jpg', title: 'Escritorio francés con banqueta tapizada' },
    { file: 'escritorio-hecho-a-medida-en-melaminico-blanco1.jpg', title: 'Escritorio hecho a medida en melamínico blanco' },
    { file: 'escritorio-personalizado-en-melaminico-blanco.jpg', title: 'Escritorio personalizado en melamínico blanco' },
    { file: 'recibidor-con-varillas-de-madera-alamo-combinando-tonos.jpg', title: 'Recibidor con varillas de madera álamo combinando tonos' },
  ],
  exterior: [
    { file: 'barra-con-taburetes-en-eucaliptus.jpg', title: 'Barra con taburetes en eucaliptus' },
    { file: 'comedor-de-exterior-en-madera-eucaliptus.jpg', title: 'Comedor de exterior en madera eucaliptus' },
    { file: 'galeria-disenada-en-madera-lapacho.jpg', title: 'Galería diseñada en madera lapacho' },
    { file: 'juego-de-exterior-con-bancos-con-respaldo-y-almohadones-madera-eucaliptus.jpg', title: 'Juego de exterior con bancos con respaldo y almohadones madera eucaliptus' },
    { file: 'juego-de-exterior-con-sillones-semicirculo-en-lapacho.jpg', title: 'Juego de exterior con sillones semicírculo en lapacho' },
    { file: 'juego-de-exterior-de-mesa-y-bancos-en-eucaliptus.jpg', title: 'Juego de exterior de mesa y bancos en eucaliptus' },
    { file: 'juego-de-exterior-en-eucaliptus-con-mesa-y-bancos.png', title: 'Juego de exterior en eucaliptus con mesa y bancos' },
    { file: 'juego-de-exterior-en-lapacho-con-estructura-de-hierro1.jpg', title: 'Juego de exterior en lapacho con estructura de hierro' },
    { file: 'juego-de-exterior-en-lapacho-con-pergola.jpg', title: 'Juego de exterior en lapacho con pérgola' },
    { file: 'juego-de-exterior-en-lapacho-lustrado-oscuro.jpg', title: 'Juego de exterior en lapacho lustrado oscuro' },
    { file: 'juego-de-exterior-en-lapacho-para-balcon-.jpg', title: 'Juego de exterior en lapacho para balcón' },
    { file: 'juego-de-exterior-en-lapacho.jpg', title: 'Juego de exterior en lapacho' },
    { file: 'juego-de-sillones-con-posabrazos-en-lapacho-con-almohadones.jpg', title: 'Juego de sillones con posabrazos en lapacho con almohadones' },
    { file: 'juego-de-sillones-sin-posabrazos-en-madera-eucaliptus.jpg', title: 'Juego de sillones sin posabrazos en madera eucaliptus' },
    { file: 'living-exterior-en-lapacho-con-pergola-.jpg', title: 'Living exterior en lapacho con pérgola' },
    { file: 'mesa-de-comedor-en-lapacho-con-base-de-hierro.jpg', title: 'Mesa de comedor en lapacho con base de hierro' },
    { file: 'mesa-de-exterior-en-eucaliptus-con-banco-.jpg', title: 'Mesa de exterior en eucaliptus con banco' },
    { file: 'mesa-de-exterior-en-eucaliptus-con-base-de-hierro.jpg', title: 'Mesa de exterior en eucaliptus con base de hierro' },
    { file: 'mesa-de-living-de-exterior-en-madera-lapacho.jpg', title: 'Mesa de living de exterior en madera lapacho' },
    { file: 'mesada-para-kamado-en-eucaliptus.jpg', title: 'Mesada para kamado en eucaliptus' },
    { file: 'reposeras-con-colchoneta.jpg', title: 'Reposeras con colchoneta' },
    { file: 'reposeras-para-piscinas-con-colchoneta.jpg', title: 'Reposeras para piscinas con colchoneta' },
    { file: 'sillones-con-posabrazos-a-pedido-del-cliente.jpg', title: 'Sillones con posabrazos a pedido del cliente' },
    { file: 'sillones-con-posabrazos-mas-bajo.jpg', title: 'Sillones con posabrazos más bajo' },
    { file: 'sillones-con-tablitas-a-pedido-del-cliente-en-madera-eucaliptus.jpg', title: 'Sillones con tablitas a pedido del cliente en madera eucaliptus' },
    { file: 'sillones-de-exterior-con-almohadones-de-uno-y-dos-cuerpos-en-madera-eucaliptus.jpg', title: 'Sillones de exterior con almohadones de uno y dos cuerpos en madera eucaliptus' },
    { file: 'sillones-de-tres-cuerpos-con-varillas-verticales-en-lapacho.jpg', title: 'Sillones de tres cuerpos con varillas verticales en lapacho' },
    { file: 'sillones-sin-posabrazos-con-almohadones.jpg', title: 'Sillones sin posabrazos con almohadones' },
    { file: 'sillon-con-posabrazos-en-madera-eucaliptus.jpg', title: 'Sillón con posabrazos en madera eucaliptus' },
    { file: 'sillon-curvo-en-alamo.jpg', title: 'Sillón curvo en álamo' },
    { file: 'sillon-semicirculo-frente-2.10-con-almohadones.jpg', title: 'Sillón semicírculo frente 2.10 con almohadones' },
    { file: 'sillon-sin-posabrazos-de-frente-en-eucaliptus.jpg', title: 'Sillón sin posabrazos de frente en eucaliptus' },
  ],
  'hierro-y-madera': [
    { file: 'aparador-de-hierro-y-madera.jpg', title: 'Aparador de hierro y madera' },
    { file: 'cristalero-con-moldura-y-puertas-de-hierro.jpg', title: 'Cristalero con moldura y puertas de hierro' },
    { file: 'juego-de-living-en-hierro-y-madera.jpg', title: 'Juego de living en hierro y madera' },
    { file: 'mesa-de-arrimo-en-alamo-con-detalles-en-hierro.jpg', title: 'Mesa de arrimo en álamo con detalles en hierro' },
    { file: 'mesa-de-comedor-con-tapa-eucaliptus-con-base-de-hierro.jpg', title: 'Mesa de comedor con tapa eucaliptus con base de hierro' },
    { file: 'mesa-de-exterior.jpg', title: 'Mesa de exterior' },
    { file: 'mesa-de-living-doble-en-fresno-de-hierro-y-madera.jpg', title: 'Mesa de living doble en fresno de hierro y madera' },
    { file: 'mesa-de-luz-con-cajon-de-alamo-arenado-con-base-de-hierro.jpg', title: 'Mesa de luz con cajón de álamo arenado con base de hierro' },
    { file: 'mesas-de-living-con-base-de-hierro-y-tapa-de-fresno-arenado.jpg', title: 'Mesas de living con base de hierro y tapa de fresno arenado' },
    { file: 'mesas-de-living-con-base-de-hierro.jpg', title: 'Mesas de living con base de hierro' },
    { file: 'mesas-nido-con-base-de-hierro.jpg', title: 'Mesas nido con base de hierro' },
    { file: 'mesita-de-luz-con-hierro-y-madera.jpg', title: 'Mesita de luz con hierro y madera' },
    { file: 'rack-de-alamo-con-estructura-de-hierro.jpg', title: 'Rack de álamo con estructura de hierro' },
    { file: 'rack-de-hierro-y-madera-con-diseno-personalizado.jpg', title: 'Rack de hierro y madera con diseño personalizado' },
    { file: 'rack-de-hierro-y-madera.jpg', title: 'Rack de hierro y madera' },
    { file: 'ropero-con-puertas-de-granero-y-combinacion-de-maderas.jpg', title: 'Ropero con puertas de granero y combinación de maderas' },
  ],
  'dormitorios-ninos': [
    { file: 'butaca-princesita-tapizada.jpeg', title: 'Butaca Princesita tapizada' },
    { file: 'cama-casita-con-marinera.jpg', title: 'Cama casita con marinera' },
    { file: 'cama-casita-en-madera-alamo.jpg', title: 'Cama casita en madera álamo' },
    { file: 'cama-cucheta-blanca.jpg', title: 'Cama cucheta blanca' },
    { file: 'cama-cucheta-con-cajones-con-baranda-y-escalera.jpg', title: 'Cama cucheta con cajones con baranda y escalera' },
    { file: 'cama-cucheta-con-escalera-fija-y-marinera-en-eucaliptus.jpg', title: 'Cama cucheta con escalera fija y marinera en eucaliptus' },
    { file: 'cama-cucheta-con-marinera-escalera-y-biblioteca-auxiliar.jpg', title: 'Cama cucheta con marinera, escalera y biblioteca auxiliar' },
    { file: 'cama-cucheta-con-marinera.jpg', title: 'Cama cucheta con marinera' },
    { file: 'cama-cucheta-en-l.jpg', title: 'Cama cucheta en L' },
    { file: 'cama-cucheta-medio-punto-con-varillas.jpg', title: 'Cama cucheta medio punto con varillas' },
    { file: 'cama-cuna-con-varillas-madera-cedro.jpg', title: 'Cama cuna con varillas madera cedro' },
    { file: 'cama-cuna-transformable-con-cajonera-y-arcon.jpg', title: 'Cama cuna transformable con cajonera y árcon' },
    { file: 'cama-de-nino-con-casita-didactica.jpg', title: 'Cama de niño con casita didáctica' },
    { file: 'cama-de-una-plaza-con-ranuras-y-marinera.jpeg', title: 'Cama de una plaza con ranuras y marinera' },
    { file: 'cama-de-una-plaza-con-respaldo-con-ranuras.jpeg', title: 'Cama de una plaza con respaldo con ranuras' },
    { file: 'cama-didactica.jpg', title: 'Cama didáctica' },
    { file: 'cama-marinera-simple.jpeg', title: 'Cama marinera simple' },
    { file: 'cucheta-con-escalera-baranda-y-marinera-en-alamo-lustrado-de-grises-2.jpg', title: 'Cucheta con escalera, baranda y marinera en álamo lustrado de grises' },
    { file: 'cucheta-doble-patinada-hecha-a-medida.jpeg', title: 'Cucheta doble patinada hecha a medida' },
    { file: 'escritorio-delfi-con-repisa.jpg', title: 'Escritorio Delfi con repisa' },
    { file: 'escritorio-combinando-tonos.jpg', title: 'Escritorio combinando tonos' },
    { file: 'escritorio-de-ninos-con-biblioteca-hecho-a-medida.jpg', title: 'Escritorio de niños con biblioteca hecho a medida' },
    { file: 'escritorio-frances-con-banqueta-tapizada.jpg', title: 'Escritorio francés con banqueta tapizada' },
    { file: 'mesa-de-luz-dos-cajones-y-hueco.jpg', title: 'Mesa de luz dos cajones y hueco' },
  ],
  'banos-y-cocinas': [
    { file: 'alacena-de-cocina-de-tres-puertas-blancas.jpg', title: 'Alacena de cocina de tres puertas blancas' },
    { file: 'amoblamiento-de-bano-en-madera-cerejeira.jpg', title: 'Amoblamiento de baño en madera cerejeira' },
    { file: 'amoblamiento-de-cocina-con-aereos-y-bajo-mesada-lustrado-de-blanco.jpg', title: 'Amoblamiento de cocina con aéreos y bajo mesada lustrado de blanco' },
    { file: 'amoblamiento-de-cocina-con-cajoneras-y-aereos-en-cedro.jpg', title: 'Amoblamiento de cocina con cajoneras y aéreos en cedro' },
    { file: 'amoblamiento-de-cocina-en-alamo-lustrado-de-blanco.jpg', title: 'Amoblamiento de cocina en álamo lustrado de blanco' },
    { file: 'amoblamiento-de-cocina-en-melaminico-blanco.jpg', title: 'Amoblamiento de cocina en melamínico blanco' },
    { file: 'amoblamiento-de-cocina-en-melaminico-blanco-1.jpg', title: 'Amoblamiento de cocina en melamínico blanco (lineal)' },
    { file: 'amoblamiento-de-cocina-en-melaminico-blanco-3.jpg', title: 'Amoblamiento de cocina en melamínico blanco (en U)' },
    { file: 'amoblamiento-de-cocina-en-melaminico-blanco-con-perfil-de-aluminio.jpg', title: 'Amoblamiento de cocina en melamínico blanco con perfil de aluminio' },
    { file: 'bajo-mesada-clasico.jpg', title: 'Bajo mesada clásico' },
    { file: 'bajo-mesada-de-bano-colgado.jpg', title: 'Bajo mesada de baño colgado' },
    { file: 'bajo-mesada-de-bano-con-6-cajones-en-fresno.jpg', title: 'Bajo mesada de baño con 6 cajones en fresno' },
    { file: 'bajo-mesada-de-bano-con-chanfle-en-cedro.jpg', title: 'Bajo mesada de baño con chanfle en cedro' },
    { file: 'bajo-mesada-de-bano-con-despojador-en-madera-fresno.jpg', title: 'Bajo mesada de baño con despojador en madera fresno' },
    { file: 'bajo-mesada-de-bano-con-espejo-en-fresno-arenado.jpg', title: 'Bajo mesada de baño con espejo en fresno arenado' },
    { file: 'bajo-mesada-de-bano-diseno-a-medida-en-fresno.jpg', title: 'Bajo mesada de baño diseño a medida en fresno' },
    { file: 'bajo-mesada-de-bano-en-alamo.jpg', title: 'Bajo mesada de baño en álamo' },
    { file: 'bajo-mesada-de-bano-en-alamo-1.jpg', title: 'Bajo mesada de baño en álamo (piedra negra)' },
    { file: 'bajo-mesada-de-bano-en-cedro.jpg', title: 'Bajo mesada de baño en cedro' },
    { file: 'bajo-mesada-de-bano-en-finger.jpg', title: 'Bajo mesada de baño en finger' },
    { file: 'bajo-mesada-de-bano-en-melaminico-blanco.jpg', title: 'Bajo mesada de baño en melamínico blanco' },
    { file: 'bajo-mesada-de-bano-en-melaminico.jpg', title: 'Bajo mesada de baño en melamínico' },
    { file: 'bajo-mesada-de-cocina-en-madera-nacional-lustrada-de-blanco.jpg', title: 'Bajo mesada de cocina en madera nacional lustrada de blanco' },
    { file: 'bajo-mesada-de-parrillero-en-eucaliptus.jpg', title: 'Bajo mesada de parrillero en eucaliptus' },
    { file: 'bajo-mesada-en-melaminico-blanco.jpg', title: 'Bajo mesada en melamínico blanco' },
    { file: 'bajo-mesada-y-aereo-de-cocina-en-alamo-lustrado-de-blanco.jpg', title: 'Bajo mesada y aéreo de cocina en álamo lustrado de blanco' },
    { file: 'bajo-mesada-y-aereo-de-cocina.jpg', title: 'Bajo mesada y aéreo de cocina' },
    { file: 'bano-con-tres-puertas-y-tres-cajones-en-melaminico-blanco.jpg', title: 'Baño con tres puertas y tres cajones en melamínico blanco' },
    { file: 'bano-con-un-jaon-estante.jpg', title: 'Baño con un cajón estante' },
    { file: 'cocina-con-aereo-en-fresno-y-bajo-mesada-en-melaminico-gris.jpg', title: 'Cocina con aéreo en fresno y bajo mesada en melamínico gris' },
    { file: 'despojador-en-fresno-arenado.jpg', title: 'Despojador en fresno arenado' },
    { file: 'espejo-redondo-en-alamo.jpg', title: 'Espejo redondo en álamo' },
    { file: 'estante-a-pedido-del-cliente1.jpg', title: 'Estante a pedido del cliente' },
    { file: 'estanteria-con-mesa-desayunador-en-madera-alamo.jpg', title: 'Estantería con mesa desayunador en madera álamo' },
    { file: 'mesada-de-bano-en-alamo.jpg', title: 'Mesada de baño en álamo' },
    { file: 'mesada-doble-de-bano-en-alamo.jpg', title: 'Mesada doble de baño en álamo' },
    { file: 'mueble-de-bano-con-espejo-en-alamo.jpg', title: 'Mueble de baño con espejo en álamo' },
    { file: 'mueble-de-bano-solo-estantes.jpeg', title: 'Mueble de baño solo estantes' },
    { file: 'mueble-de-bano-con-cajones-y-estantes-lustrado-con-patina-blanca.jpg', title: 'Mueble de baño con cajones y estantes lustrado con pátina blanca' },
    { file: 'mueble-de-bano-con-venecianas-en-cedro.jpg', title: 'Mueble de baño con venecianas en cedro' },
    { file: 'mueble-de-bano-en-alamo.jpg', title: 'Mueble de baño en álamo' },
    { file: 'mueble-de-bano-en-madera-alamo.jpg', title: 'Mueble de baño en madera álamo' },
    { file: 'mueble-de-bano-tipo-banco-carpintero.jpg', title: 'Mueble de baño tipo banco carpintero' },
    { file: 'muebles-para-playroom.jpg', title: 'Muebles para playroom' },
    { file: 'repisa-de-melaminico-gris-grafito.jpg', title: 'Repisa de melamínico gris grafito' },
  ],
  barbacoas: [
    { file: 'amoblamiento-de-barbacoa-con-botellero-y-barra-en-alamo.jpg', title: 'Amoblamiento de barbacoa con botellero y barra en álamo' },
    { file: 'bar-libro-en-cedro.jpeg', title: 'Bar libro en cedro' },
    { file: 'barra-de-bar-en-alamo.jpg', title: 'Barra de bar en álamo' },
    { file: 'barra-de-bar-en-madera-eucaliptus.jpg', title: 'Barra de bar en madera eucaliptus' },
    { file: 'barra-de-bar-y-taburetes-con-suela-en-alamo.jpg', title: 'Barra de bar y taburetes con suela en álamo' },
    { file: 'botellero-realizado-a-medida-en-alamo.jpg', title: 'Botellero realizado a medida en álamo' },
    { file: 'diseno-para-espacios-reducidos-en-lapacho.jpg', title: 'Diseño para espacios reducidos en lapacho' },
    { file: 'juego-de-comedor-en-lapacho.jpg', title: 'Juego de comedor en lapacho' },
    { file: 'juego-de-comedor-para-espacios-reducidos-en-eucaliptus.jpg', title: 'Juego de comedor para espacios reducidos en eucaliptus' },
    { file: 'juego-de-exterior-unique.jpg', title: 'Juego de exterior Unique' },
    { file: 'juego-de-exterior-patas-con-x.jpg', title: 'Juego de exterior patas con X' },
    { file: 'mesa-de-barbacoa-con-madera-en-eucaliptus.jpg', title: 'Mesa de barbacoa con madera en eucaliptus' },
    { file: 'mesa-de-comedor-uxmal-en-madera-eucaliptus.jpg', title: 'Mesa de comedor Uxmal en madera eucaliptus' },
    { file: 'mesa-de-comedor-cuadrada-con-bancos-con-respaldo-en-eucaliptus.jpg', title: 'Mesa de comedor cuadrada con bancos con respaldo en eucaliptus' },
    { file: 'mesa-de-exterior-con-bancos-sin-respaldo-en-madera-eucaliptus.jpg', title: 'Mesa de exterior con bancos sin respaldo en madera eucaliptus' },
    { file: 'mesa-de-living-con-patas-rectas-de-hierro.jpg', title: 'Mesa de living con patas rectas de hierro' },
    { file: 'mesa-de-living-con-tapa-de-tronco-en-eucaliptus.jpg', title: 'Mesa de living con tapa de tronco en eucaliptus' },
    { file: 'mesa-de-living-en-eucaliptus-con-tablones-arrimados.jpg', title: 'Mesa de living en eucaliptus con tablones arrimados' },
    { file: 'mesa-de-living-rustica-de-exterior.jpg', title: 'Mesa de living rústica de exterior' },
    { file: 'mesa-pata-en-x-con-bancos-con-respaldo-madera-alamo.jpg', title: 'Mesa pata en X con bancos con respaldo madera álamo' },
    { file: 'mesa-y-bancos-con-hierro-planchuela.jpg', title: 'Mesa y bancos con hierro planchuela' },
    { file: 'mesa-y-bancos-con-respaldo-en-lapacho.jpg', title: 'Mesa y bancos con respaldo en lapacho' },
    { file: 'taburete-tapizado-total.jpg', title: 'Taburete tapizado total' },
    { file: 'taburetes-tapizados-total.jpg', title: 'Taburetes tapizados total' },
  ],
  living: [
    { file: 'aparador-de-dos-puertas-con-dos-cajones-en-madera-alamo.jpg', title: 'Aparador de dos puertas con dos cajones en madera álamo' },
    { file: 'aparador-especial-con-combinacion-de-colores-y-materiales.jpg', title: 'Aparador especial con combinación de colores y materiales' },
    { file: 'banqueta-apoya-pie-cuchara-tapizada.jpg', title: 'Banqueta apoya pie cuchara tapizada' },
    { file: 'butaca-paulina-tapizada-con-tela-easy-clean.jpg', title: 'Butaca Paulina tapizada con tela easy clean' },
    { file: 'butaca-con-esterilla-asiento-y-respaldo.jpg', title: 'Butaca con esterilla asiento y respaldo' },
    { file: 'butaca-con-rafia.jpg', title: 'Butaca con rafia' },
    { file: 'butaca-modelo-paulina.jpeg', title: 'Butaca modelo Paulina' },
    { file: 'mesa-de-living-campana.jpg', title: 'Mesa de living Campaña' },
    { file: 'mesa-de-living-catena-con-dos-pies-centrales.jpg', title: 'Mesa de living Catena con dos pies centrales' },
    { file: 'mesa-de-living-faraonica.jpg', title: 'Mesa de living Faraónica' },
    { file: 'mesa-de-living-faraonica-de-cedro.jpg', title: 'Mesa de living Faraónica de cedro' },
    { file: 'mesa-de-living-indonesa.jpg', title: 'Mesa de living Indonesa' },
    { file: 'mesa-de-living-uxmal.jpg', title: 'Mesa de living Uxmal' },
    { file: 'mesa-de-living-con-base-de-hierro-en-u.jpg', title: 'Mesa de living con base de hierro en U' },
    { file: 'mesa-de-living-con-base-de-hierro-y-tapa-de-alamo.jpg', title: 'Mesa de living con base de hierro y tapa de álamo' },
    { file: 'mesa-de-living-con-base-de-hierro-y-tapa-de-vidrio.jpg', title: 'Mesa de living con base de hierro y tapa de vidrio' },
    { file: 'mesa-de-living-con-base-en-u.jpg', title: 'Mesa de living con base en U' },
    { file: 'mesa-de-living-con-patas-inclinadas.jpg', title: 'Mesa de living con patas inclinadas' },
    { file: 'mesa-de-living-con-patas-rectas-de-hierro.jpg', title: 'Mesa de living con patas rectas de hierro' },
    { file: 'mesa-de-living-con-sistema-elevadizo.jpg', title: 'Mesa de living con sistema elevadizo' },
    { file: 'mesa-de-living-con-tapa-de-tronco-en-eucaliptus.jpg', title: 'Mesa de living con tapa de tronco en eucaliptus' },
    { file: 'mesa-de-living-con-tapiz-en-madera-alamo.jpg', title: 'Mesa de living con tapiz en madera álamo' },
    { file: 'mesa-de-living-cuatro-patas-rectas.jpg', title: 'Mesa de living cuatro patas rectas' },
    { file: 'mesa-de-living-de-fresno-con-base-de-hierro.jpg', title: 'Mesa de living de fresno con base de hierro' },
    { file: 'mesa-de-living-doble-t-de-7-cm-de-espesor.jpg', title: 'Mesa de living doble T de 7 cm de espesor' },
    { file: 'mesa-de-living-doble-t-de-espesor-7-cm.jpg', title: 'Mesa de living doble T de espesor 7 cm' },
    { file: 'mesa-de-living-doble-t-fresno-arenado.jpg', title: 'Mesa de living doble T fresno arenado' },
    { file: 'mesa-de-living-doble-t.jpg', title: 'Mesa de living doble T' },
    { file: 'mesa-de-living-doble-con-base-en-u.jpg', title: 'Mesa de living doble con base en U' },
    { file: 'mesa-de-living-doble-diseno-doble-t.jpg', title: 'Mesa de living doble diseño doble T' },
    { file: 'mesa-de-living-doble-en-fresno-arenado-con-base-de-hierro.jpg', title: 'Mesa de living doble en fresno arenado con base de hierro' },
    { file: 'mesa-de-living-doble-madera-en-alamo-con-puff-tapizado.jpg', title: 'Mesa de living doble madera en álamo con puff tapizado' },
    { file: 'mesa-de-living-en-u-con-base.jpg', title: 'Mesa de living en U con base' },
    { file: 'mesa-de-living-en-eucaliptus-con-tablones-arrimados.jpg', title: 'Mesa de living en eucaliptus con tablones arrimados' },
    { file: 'mesa-de-living-en-fresno-con-patas-inclinadas.jpg', title: 'Mesa de living en fresno con patas inclinadas' },
    { file: 'mesa-de-living-especial.jpg', title: 'Mesa de living especial' },
    { file: 'mesa-de-living-maciza-en-lapacho.jpg', title: 'Mesa de living maciza en lapacho' },
    { file: 'mesa-de-living-moderna-en-madera-alamo.jpg', title: 'Mesa de living moderna en madera álamo' },
    { file: 'mesa-de-living-moderna-patas-rectas.jpg', title: 'Mesa de living moderna patas rectas' },
    { file: 'mesa-de-living-moderna.jpg', title: 'Mesa de living moderna' },
    { file: 'mesa-de-living-pata-modelo-uno.jpg', title: 'Mesa de living pata modelo uno' },
    { file: 'mesa-de-living-pata-recta.jpg', title: 'Mesa de living pata recta' },
    { file: 'mesa-de-living-patas-inclinadas.jpg', title: 'Mesa de living patas inclinadas' },
    { file: 'mesa-de-living-rustica-de-exterior.jpg', title: 'Mesa de living rústica de exterior' },
    { file: 'mesa-redonda-de-living-nido-de-fresno-con-base-de-hierro.jpg', title: 'Mesa redonda de living nido de fresno con base de hierro' },
    { file: 'rack-con-botellero-y-puertas-con-esterilla.jpg', title: 'Rack con botellero y puertas con esterilla' },
    { file: 'rack-con-puertas-con-esterilla-en-madera-alamo.jpg', title: 'Rack con puertas con esterilla en Madera álamo' },
    { file: 'rack-con-puertas-corredizas-de-hierro-en-madera-alamo.jpg', title: 'Rack con puertas corredizas de hierro en madera álamo' },
    { file: 'rack-de-cuatro-cajones.jpg', title: 'Rack de cuatro cajones' },
    { file: 'trinchante-2-puertas-con-varillas-y-dos-cajones.jpg', title: 'Trinchante 2 puertas con varillas y dos cajones' },
    { file: 'trinchante-de-cuatro-puertas-con-varillas-de-madera-alamo.jpg', title: 'Trinchante de cuatro puertas con varillas de madera álamo' },
  ],
  dormitorios: [
    { file: 'butaca-modelo-paulina.jpeg', title: 'Butaca modelo Paulina' },
    { file: 'comoda-de-5-cajones-en-madera-cedro.jpg', title: 'Cómoda de 5 cajones en madera cedro' },
    { file: 'comoda-recta-8-cajones.jpg', title: 'Cómoda recta 8 cajones' },
    { file: 'dormitorio.jpg', title: 'Dormitorio' },
    { file: 'mesa-de-luz-3-cajones-combinando-patina-con-betun-y-color-roble..jpg', title: 'Mesa de luz 3 cajones combinando pátina con betún y color roble' },
    { file: 'mesa-de-luz-delfi-2-cajones.jpeg', title: 'Mesa de luz Delfi 2 cajones' },
    { file: 'mesa-de-luz-con-cajon-de-alamo-arenado-con-base-de-hierro.jpg', title: 'Mesa de luz con cajón de álamo arenado con base de hierro' },
    { file: 'mesa-de-luz-dos-cajones-y-hueco-frente-60-cm.jpeg', title: 'Mesa de luz dos cajones y hueco frente 60 cm' },
    { file: 'mesa-de-luz-dos-cajones.jpeg', title: 'Mesa de luz dos cajones' },
    { file: 'mesa-de-luz-ingletada-con-dos-cajones-de-madera-en-alamo.jpg', title: 'Mesa de luz ingletada con dos cajones de madera en álamo' },
    { file: 'respaldo-aro-de-15-cm-tapizado.jpg', title: 'Respaldo aro de 15 cm tapizado' },
    { file: 'respaldo-capitoneado-de-1-plaza.jpg', title: 'Respaldo capitoneado de 1 plaza' },
    { file: 'respaldo-con-moldura-tapizado.jpg', title: 'Respaldo con moldura tapizado' },
    { file: 'respaldo-curvo-con-moldura-tapizado.jpg', title: 'Respaldo curvo con moldura tapizado' },
    { file: 'respaldo-frances-con-moldura.jpg', title: 'Respaldo francés con moldura' },
    { file: 'respaldo-macizo-con-moldura-patinado.jpg', title: 'Respaldo macizo con moldura patinado' },
    { file: 'respaldo-macizo-con-moldura.jpeg', title: 'Respaldo macizo con moldura' },
    { file: 'respaldo-modelo-5-x-patinado.jpg', title: 'Respaldo modelo 5X patinado' },
    { file: 'respaldo-tapizado-italia.jpg', title: 'Respaldo tapizado Italia' },
    { file: 'respaldo-tapizado-aro-de-5-cm-con-moldura.jpeg', title: 'Respaldo tapizado aro de 5 cm con moldura' },
    { file: 'respaldo-tapizado-capitoneado-madera-fresno.jpeg', title: 'Respaldo tapizado capitoneado madera fresno' },
    { file: 'respaldo-tapizado-con-medio-punto-y-tachas.jpg', title: 'Respaldo tapizado con medio punto y tachas' },
    { file: 'respaldo-torneado-con-moldura-y-tapizado.jpg', title: 'Respaldo torneado con moldura y tapizado' },
    { file: 'ropero-con-puertas-corredizas-madera-alamo-lustrado-de-blanco.jpg', title: 'Ropero con puertas corredizas madera álamo lustrado de blanco' },
  ],
  comedores: [
    { file: 'barra-de-cocina-con-taburetes-tapizados.jpg', title: 'Barra de cocina con taburetes tapizados' },
    { file: 'estanteria-con-mesa-desayunador-en-madera-alamo.jpg', title: 'Estantería con mesa desayunador en madera álamo' },
    { file: 'juego-de-comedor-diario-oval.jpg', title: 'Juego de comedor diario Oval' },
    { file: 'mesa-con-varillas-madera-alamo.jpg', title: 'Mesa con varillas madera álamo' },
    { file: 'mesa-de-comedor-campana-pie-central.jpg', title: 'Mesa de comedor Campaña pie central' },
    { file: 'mesa-de-comedor-campana.jpg', title: 'Mesa de comedor Campaña' },
    { file: 'mesa-de-comedor-catena-2.jpg', title: 'Mesa de comedor Catena 2' },
    { file: 'mesa-de-comedor-catena-con-pie-central.jpg', title: 'Mesa de comedor Catena con pie central' },
    { file: 'mesa-de-comedor-catena-de-fresno-con-patina-blanca.jpg', title: 'Mesa de comedor Catena de fresno con pátina blanca' },
    { file: 'mesa-de-comedor-catena-diametro-120-extensible-en-madera-alamo.jpg', title: 'Mesa de comedor Catena diámetro 120 extensible en madera álamo' },
    { file: 'mesa-de-comedor-catena-especial-en-fresno.jpg', title: 'Mesa de comedor Catena especial en fresno' },
    { file: 'mesa-de-comedor-catena-extensible.jpg', title: 'Mesa de comedor Catena extensible' },
    { file: 'mesa-de-comedor-catena-madera-alamo-3.jpg', title: 'Mesa de comedor Catena madera álamo' },
    { file: 'mesa-de-comedor-catena-pie-central.jpg', title: 'Mesa de comedor Catena pie central' },
    { file: 'mesa-de-comedor-catena-rectangular.jpg', title: 'Mesa de comedor Catena rectangular' },
    { file: 'mesa-de-comedor-catena.jpg', title: 'Mesa de comedor Catena' },
    { file: 'mesa-de-comedor-con-maderas-recicladas.jpg', title: 'Mesa de comedor con maderas recicladas' },
    { file: 'mesa-de-comedor-cuatro-patas-rectas.jpg', title: 'Mesa de comedor cuatro patas rectas' },
    { file: 'mesa-de-comedor-de-cipres-sillas-respaldo-con-asiento-de-rattan.jpg', title: 'Mesa de comedor de ciprés sillas respaldo con asiento de rattan' },
    { file: 'mesa-de-comedor-en-alamo-arenado-recta.jpg', title: 'Mesa de comedor en álamo arenado recta' },
    { file: 'mesa-de-comedor-en-cipres-con-base-de-hierro.jpg', title: 'Mesa de comedor en ciprés con base de hierro' },
    { file: 'mesa-de-comedor-en-fresno-arenado.jpg', title: 'Mesa de comedor en fresno arenado' },
    { file: 'mesa-de-comedor-en-v.jpg', title: 'Mesa de comedor en V' },
    { file: 'mesa-de-comedor-fresno-arenado.jpg', title: 'Mesa de comedor fresno arenado' },
    { file: 'mesa-de-comedor-madera-roble-con-sillas-con-esterilla.jpg', title: 'Mesa de comedor madera roble con sillas con esterilla' },
    { file: 'mesa-de-comedor-moderna.jpg', title: 'Mesa de comedor moderna' },
    { file: 'mesa-de-comedor-nordica.jpg', title: 'Mesa de comedor Nórdica' },
    { file: 'mesa-de-comedor-pata-en-x1.jpg', title: 'Mesa de comedor pata en X' },
    { file: 'mesa-de-comedor-patas-inclinadas.jpg', title: 'Mesa de comedor patas inclinadas' },
    { file: 'mesa-de-comedor-rustica1.jpg', title: 'Mesa de comedor rústica' },
    { file: 'mesa-de-comedor-rustica2.jpg', title: 'Mesa de comedor rústica (barbacoa)' },
    { file: 'mesa-de-comedor-uxmal-con-patas-de-13-x-13.jpg', title: 'Mesa de comedor Uxmal con patas de 13×13' },
    { file: 'mesa-de-comedor-uxmal-pata-9-x-9-cm.jpg', title: 'Mesa de comedor Uxmal pata 9×9 cm' },
  ],
}

export function getGalleryItems(slug: string) {
  const photos = GALLERY[slug] ?? []
  return photos.map((p, i) => ({
    id: -(i + 1),
    category_id: 0,
    image_url: `${BASE}/${slug}/${p.file}`,
    title: p.title,
    description: null as string | null,
    created_at: '',
  }))
}
